### ISSUE TITLE
Restore does not find cache key even though it seems to exist

### ISSUE THREAD

**Issue by jbergstroem** [MartijnHols/actions-cache#7]
Given the following yaml:
```yaml
      - name: Check if cache key exists
        uses: martijnhols/actions-cache/check@v3.0.11
        id: cache_exists
        with:
          path: .venv
          key: ${{ runner.os }}-python-deps-${{ hashFiles('poetry.lock') }}

      - name: Set up Python
        uses: actions/setup-python@v4
        if: steps.cache_exists.outputs.cache-hit != 'true'
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Restore dependency cache
        uses: actions/cache@v3
        if: steps.cache_exists.outputs.cache-hit != 'true'
        id: deps-cache
        with:
          path: .venv
          key: ${{ runner.os }}-python-deps-${{ hashFiles('poetry.lock') }}
```

I get this output:
<img width="801" alt="Screenshot 2023-06-29 at 7 47 57 PM" src="https://github.com/MartijnHols/actions-cache/assets/176984/8c3d4372-b531-412b-961f-6c7e99e80277">

Comparing the keys, they look identical (copy pasted manually from output):
- `Linux-python-deps-905d6047b1ef7816097d7c2ed5d59e9334470b45f129b2df87b40a4f33058e2a`
- `Linux-python-deps-905d6047b1ef7816097d7c2ed5d59e9334470b45f129b2df87b40a4f33058e2a`

**Comment by jbergstroem** [comment]
Resorted to just calling the cache endpoint via curl instead:
```yaml
- name: Check if cache key exists
  id: cache_exists
  env:
    url: "${{ github.api_url }}/repos/${{ github.repository }}/actions/caches"
    key: ${{ runner.os }}-python-deps-${{ hashFiles('poetry.lock') }}
  run: |
    curl -s \
    -H "Accept: application/vnd.github+json" \
    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
    -H "X-GitHub-Api-Version: 2022-11-28" \
    "${{ env.url }}?key=${{ env.key }}" | jq -r '"cache-hit=" + (.total_count > 0 | tostring)' >> "$GITHUB_OUTPUT"

- name: Set up Python
  uses: actions/setup-python@v4
  if: steps.cache_exists.outputs.cache-hit != 'true'
  with:
    python-version: ${{ env.PYTHON_VERSION }}
```
